=== Wifly413/Proyecto-Intermodular-ASIR-Guillermo-Duran-Cortes/LENGUAJE-MARCAS/xml/modelo.dtd
<!ELEMENT infraestructura (redes, dispositivos)>
<!ATTLIST infraestructura
    empresa CDATA #REQUIRED>

<!ELEMENT redes (vlan+)> 

<!ELEMENT vlan (ip, gateway)>
<!ATTLIST vlan
    id ID #REQUIRED
    nombre CDATA #REQUIRED>

<!ELEMENT ip_red (#PCDATA)>
<!ELEMENT gateway (#PCDATA)>

<!ELEMENT dispositivos (host*)>

<!ELEMENT host (nombre, ip)>
<!ATTLIST host
    id ID #REQUIRED
    vlan_ref IDREF #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ip (#PCDATA)>

=== Wifly413/Proyecto-Intermodular-ASIR-Guillermo-Duran-Cortes/LENGUAJE-MARCAS/xml/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="transform.xsl"?>
<!DOCTYPE infraestructura SYSTEM "modelo.dtd">

<!-- Voy a hacer la red que pantee en el intermodular ya que lo sugeriste en la clase-->

<!-- Es bastante sencillo dos hijos la red con las vlan y los dispositos sde cada vlan(iba a poner como una muestra pero realmente si quiero pintar la red entera los tendre que meter todos-->

<infraestructura empresa='BugiSoft'>
    
    <redes>
        <vlan id='v10' nombre='ADMIN_RECEP'>
            <ip>192.168.10.0</ip>
            <gateway>192.168.10.1</gateway>
        </vlan>
        <vlan id='v20' nombre='DIRECCION'>
            <ip>192.168.20.0</ip>
            <gateway>192.168.20.1</gateway>
        </vlan>
        <vlan id='v30' nombre='DESARROLLO'>
            <ip>192.168.30.0</ip>
            <gateway>192.168.30.1</gateway>
        </vlan>
        <vlan id='v40' nombre='SOPORTE_QA'>
            <ip>192.168.40.0</ip>
            <gateway>192.168.40.1</gateway>
        </vlan>
        <vlan id='v50' nombre='FORMACION'>
            <ip>192.168.50.0</ip>
            <gateway>192.168.50.1</gateway>
        </vlan>
        <vlan id='v60' nombre='SERVIDORES'>
            <ip>192.168.60.0</ip>
            <gateway>192.168.60.1</gateway>
        </vlan>
        <vlan id='v70' nombre='INVITADOS'>
            <ip>192.168.70.0</ip>
            <gateway>192.168.70.1</gateway>
        </vlan>
        <vlan id='v99' nombre='GESTION_MGMT'>
            <ip>192.168.99.0</ip>
            <gateway>192.168.99.1</gateway>
        </vlan>
    </redes>

    <dispositivos>
        <host id='h10' vlan_ref='v10'>
            <nombre>PC-ADM-01</nombre>
            <ip>192.168.10.11</ip>
        </host>
        <host id='h20' vlan_ref='v20'>
            <nombre>PC-DIR-01</nombre>
            <ip>192.168.20.11</ip>
        </host>
        <host id='h30' vlan_ref='v30'>
            <nombre>PC-DEV-01</nombre>
            <ip>192.168.30.11</ip>
        </host>
        <host id='h40' vlan_ref='v40'>
            <nombre>PC-SOP-01</nombre>
            <ip>192.168.40.11</ip>
        </host>
        <host id='h50' vlan_ref='v50'>
            <nombre>PC-FOR-01</nombre>
            <ip>192.168.50.11</ip>
        </host>
        <host id='h60' vlan_ref='v60'>
            <nombre>SRV-DATA-01</nombre>
            <ip>192.168.60.2</ip>
        </host>
        <host id='h70' vlan_ref='v70'>
            <nombre>LAP-INVITADOS</nombre>
            <ip>192.168.70.11</ip>
        </host>
        <host id='h99' vlan_ref='v99'>
            <nombre>PC-MGMT-01</nombre>
            <ip>192.168.99.11</ip>
        </host>
    </dispositivos>

</infraestructura>
